version: '3'

services:
  database:
    container_name: ${DATABASE_SERVICE_NAME}
    restart: always
    image: postgres:latest
    shm_size: 5gb
    environment:
      POSTGRES_USER: ${DATABASE_ORIGIN_USER}
      POSTGRES_PASSWORD: ${DATABASE_ORIGIN_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db_volume:/var/lib/postgresql/data
    expose:
      - ${DATABASE_PORT}

  backend:
    container_name: ${BACKEND_SERVICE_NAME}
    restart: always
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    env_file: .env
    volumes:
      - ./slavov_backend:/code:cached
      - statics_volume:/code/static
    depends_on:
      - database
    expose:
      - ${BACKEND_PORT}
    command:
    - gunicorn
    - -c
    - gunicorn.py
    - slavov_backend.asgi:application
    - -k
    - uvicorn.workers.UvicornWorker
    - --reload

  http-server:
    container_name: ${HTTP_SERVER_SERVICE_NAME}
    restart: always
    build:
      context: .
      dockerfile: docker/http_server.Dockerfile
    environment:
      HTTP_SERVER_HOST: ${HTTP_SERVER_HOST}
      HTTP_SERVER_PORT: ${HTTP_SERVER_PORT}
      NGINX_ENVSUBST_TEMPLATE_DIR: ${HTTP_TEMPLATE_DIR}
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx/sites-available
      BACKEND_SERVICE_NAME: ${BACKEND_SERVICE_NAME}
      BACKEND_PORT: ${BACKEND_PORT}
    volumes:
      - statics_volume:/usr/share/nginx/static:ro
    expose:
      - ${HTTP_SERVER_PORT}
    ports:
      - '${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}'
    depends_on:
      - backend
      - database-admin

volumes:
  db_volume:
  statics_volume:
