# Generated by Django 4.0.4 on 2022-05-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='internal_identifier',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='код товара'),
        ),
    ]
