# Generated by Django 4.0.4 on 2022-05-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_remove_cargo_internal_identifier_alter_cargo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='id',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='код товара'),
        ),
    ]
